# Partner production model — Topic A @ 4 GB/s total load point
# (20% share, rf=3 via driver, 2x fanout)
name: Partner prod Topic A - 4GBps point
topics: 1
partitionsPerTopic: 150
messageSize: 1024
payloadFile: "payload/payload-1Kb.data"
subscriptionsPerTopic: 2
consumerPerSubscription: 150
producersPerTopic: 50
producerRate: 800000
consumerBacklogSizeGB: 0
testDurationMinutes: 30
warmupDurationMinutes: 5
